In [1]:
import pandas as pd
import os

In [2]:
path=""
year=['2016', '2017', '2018', '2019', '2020']
team=['HT', 'LT', 'SK', 'LG', 'NC', 'KT', 'HH', 'OB', 'SS', 'WO']

In [95]:
#open files
path="2019"+"_test_convert"
filename="_test_convert_bigcon_"+year[-2]+"_"

index_front = ["G_ID", "GDAY_DS", "T_ID", "VS_T_ID", "HEADER_NO", "TB_SC",
             "WHIP", "LOB", "ERA", "FIP", "H_9", "K_9", "BB_9", "HR_9",
             "oAVG", "oSLG", "oOBP", "P_WHIP_RT", "P2_WHIP_RT", "CB_WHIP_RT",
             "AVG", "OBP", "SLG", "OPS", "RC", "GPA", "BA", "SECA", "TA", "XR", "ISO",
             "wOBA", "P_HRA_RT", "DER", "PF", "H_A", "WLS"]

index_back = ["WHIP", "LOB", "ERA", "FIP", "H_9", "K_9", "BB_9", "HR_9",
             "oAVG", "oSLG", "oOBP", "P_WHIP_RT", "P2_WHIP_RT", "CB_WHIP_RT",
             "AVG", "OBP", "SLG", "OPS", "RC", "GPA", "BA", "SECA", "TA", "XR", "ISO",
             "wOBA", "P_HRA_RT", "DER", "PF", "H_A", "WLS"]

index_back=["vs_"+i for i in index_back]

#index_back[0]=index_back[0][3:]

dfs=[]

df = pd.DataFrame(columns = index_front)

for i in team:
    filepath=path+"\\"+filename+i+".csv"
    file = pd.read_csv(filepath, index_col=None, header=0)
     
    dfs.append(file)

df = pd.concat(dfs, axis=0, ignore_index=True)

In [96]:
df=df.sort_values(by=['G_ID'], axis=0)
df

,Unnamed: 0,G_ID,GDAY_DS,T_ID,VS_T_ID,HEADER_NO,TB_SC,WHIP,LOB,ERA,...,SECA,TA,XR,ISO,wOBA,P_HRA_RT,DER,PF,H_A,WLS
1008,0,20190323HHOB0,20190323,OB,HH,0,B,1.889,0.778,4.000,...,0.176,0.760,5.204,0.029,0.435,0.200,0.586,939,1,1
864,0,20190323HHOB0,20190323,HH,OB,0,T,1.375,0.625,5.625,...,0.179,0.308,0.452,0.036,0.210,0.000,0.792,939,0,0
720,0,20190323KTSK0,20190323,KT,SK,0,T,1.750,0.625,6.750,...,0.290,0.538,2.404,0.097,0.334,0.143,0.750,971,0,0
288,0,20190323KTSK0,20190323,SK,KT,0,B,1.333,0.755,4.000,...,0.194,0.536,3.580,0.083,0.314,0.200,0.680,971,1,1
432,0,20190323LGHT0,20190323,LG,HT,0,T,0.667,1.000,0.000,...,0.516,0.917,6.074,0.290,0.441,0.250,0.870,1004,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
431,143,20190930SKHH0,20190930,SK,HH,0,T,1.000,0.921,2.000,...,0.394,0.800,5.268,0.121,0.416,0.400,0.724,1025,0,1
719,143,20191001NCOB0,20191001,NC,OB,0,T,1.920,0.625,5.400,...,0.163,0.815,7.034,0.047,0.408,0.250,0.571,939,0,0
1151,143,20191001NCOB0,20191001,OB,NC,0,B,2.111,0.737,5.000,...,0.028,0.370,2.346,0.000,0.242,0.167,0.528,939,1,1
287,143,20191001WOLT0,20191001,LT,WO,0,B,1.222,0.727,1.000,...,0.150,0.760,6.342,0.075,0.379,0.267,0.692,1041,1,0
1439,143,20191001WOLT0,20191001,WO,LT,0,T,1.111,0.900,1.000,...,0.257,0.517,2.668,0.085,0.289,0.300,0.679,1041,0,1

In [108]:
new_df = pd.DataFrame(columns = index_front+index_back[1:])

for idx,_row in enumerate(df.iterrows()):
    if (idx%2==0):
        eve_row=pd.DataFrame(df[idx:idx+1], columns=index_front)
        eve_row=eve_row.reset_index()
        eve_row=eve_row.drop(columns=['index'])
    else:
        odd_row=pd.DataFrame(df[idx:idx+1], columns=index_front)
        odd_row=odd_row.drop(columns=index_front[:6])
        odd_row.columns=index_back
        odd_row=odd_row.reset_index()
        odd_row=odd_row.drop(columns=['index'])        
        
        row=pd.DataFrame(pd.concat([eve_row, odd_row], axis=1))
        
        new_df=new_df.append(row, ignore_index=True)[row.columns.tolist()]
print(new_df)
new_df.to_csv("combined_"+str(2019)+".csv")

              G_ID   GDAY_DS T_ID VS_T_ID HEADER_NO TB_SC   WHIP    LOB   ERA  \
0    20190323HHOB0  20190323   OB      HH         0     B  1.889  0.778  4.00
1    20190323KTSK0  20190323   KT      SK         0     T  1.750  0.625  6.75
2    20190323LGHT0  20190323   LG      HT         0     T  0.667  1.000  0.00
3    20190323SSNC0  20190323   NC      SS         0     B  0.667  1.000  0.00
4    20190323WOLT0  20190323   WO      LT         0     T  0.889  0.556  3.00
..             ...       ...  ...     ...       ...   ...    ...    ...   ...
715  20190929WOLT0  20190929   LT      WO         0     B  0.778  0.556  3.00
716  20190930LTLG0  20190930   LG      LT         0     B  0.667  1.000  0.00
717  20190930SKHH0  20190930   HH      SK         0     B  1.667  0.662  6.00
718  20191001NCOB0  20191001   NC      OB         0     T  1.920  0.625  5.40
719  20191001WOLT0  20191001   LT      WO         0     B  1.222  0.727  1.00

        FIP  ...  vs_SECA  vs_TA  vs_XR  vs_ISO  vs_wOBA  vs_P_HRA_RT  vs_DER  \
0    16.444  ...    0.179  0.308  0.452   0.036    0.210        0.000   0.792
1    42.750  ...    0.194  0.536  3.580   0.083    0.314        0.200   0.680
2    10.667  ...    0.171  0.429  2.192   0.057    0.248        0.231   0.579
3     4.889  ...    0.548  0.917  5.840   0.226    0.462        0.375   0.762
4     3.556  ...    0.069  0.214 -0.720   0.000    0.171        0.000   0.625
..      ...  ...      ...    ...    ...     ...      ...          ...     ...
715  11.111  ...    0.188  0.407  1.878   0.063    0.252        0.300   0.720
716   8.111  ...    0.074  0.435  1.740   0.000    0.284        0.000   0.739
717  26.000  ...    0.394  0.800  5.268   0.121    0.416        0.400   0.724
718   1.560  ...    0.028  0.370  2.346   0.000    0.242        0.167   0.528
719   7.000  ...    0.257  0.517  2.668   0.085    0.289        0.300   0.679

     vs_PF  vs_H_A  vs_WLS
0      939       0       0
1      971       1       1
2     1004       1       0
3     1035       0       0
4     1041       1       0
..     ...     ...     ...
715   1041       0       1
716    939       0       0
717   1025       0       1
718    939       1       1
719   1041       0       1

[720 rows x 68 columns]

In [117]:
def combiner(path, filename):
    year=['2016', '2017', '2018', '2019', '2020']
    team=['HT', 'LT', 'SK', 'LG', 'NC', 'KT', 'HH', 'OB', 'SS', 'WO']
    #open files
    #path="_test_convert"
    #filename="_test_convert_bigcon_"+year[-2]+"_"

    index_front = ["G_ID", "GDAY_DS", "T_ID", "VS_T_ID", "HEADER_NO", "TB_SC",
             "WHIP", "LOB", "ERA", "FIP", "H_9", "K_9", "BB_9", "HR_9",
             "oAVG", "oSLG", "oOBP", "P_WHIP_RT", "P2_WHIP_RT", "CB_WHIP_RT",
             "AVG", "OBP", "SLG", "OPS", "RC", "GPA", "BA", "SECA", "TA", "XR", "ISO",
             "wOBA", "P_HRA_RT", "DER", "PF", "H_A", "WLS"]

    index_back = ["WHIP", "LOB", "ERA", "FIP", "H_9", "K_9", "BB_9", "HR_9",
             "oAVG", "oSLG", "oOBP", "P_WHIP_RT", "P2_WHIP_RT", "CB_WHIP_RT",
             "AVG", "OBP", "SLG", "OPS", "RC", "GPA", "BA", "SECA", "TA", "XR", "ISO",
             "wOBA", "P_HRA_RT", "DER", "PF", "H_A", "WLS"]

    index_back=["vs_"+i for i in index_back]

    #index_back[0]=index_back[0][3:]
    if (os.path.isdir(os.getcwd()+"\\combined")==False):
        os.mkdir('combined')
    dfs=[]

    df = pd.DataFrame(columns = index_front)
    for y in year:
        for i in team:
            filepath=str(y)+path+"\\"+filename+str(y)+"_"+i+".csv"
            file = pd.read_csv(filepath, index_col=None, header=0)
     
            dfs.append(file)

        df = pd.concat(dfs, axis=0, ignore_index=True)
        df=df.sort_values(by=['G_ID'], axis=0)
    
        new_df = pd.DataFrame(columns = index_front+index_back[1:])

        for idx,_row in enumerate(df.iterrows()):
            if (idx%2==0):
                eve_row=pd.DataFrame(df[idx:idx+1], columns=index_front)
                eve_row=eve_row.reset_index()
                eve_row=eve_row.drop(columns=['index'])
            else:
                odd_row=pd.DataFrame(df[idx:idx+1], columns=index_front)
                odd_row=odd_row.drop(columns=index_front[:6])
                odd_row.columns=index_back
                odd_row=odd_row.reset_index()
                odd_row=odd_row.drop(columns=['index'])        
        
                row=pd.DataFrame(pd.concat([eve_row, odd_row], axis=1))
        
                new_df=new_df.append(row, ignore_index=True)[row.columns.tolist()]
        #print(new_df)
        new_df.to_csv("combined\combined_"+str(y)+".csv")

In [116]:
combiner("_test_convert","_test_convert_bigcon_")

              G_ID   GDAY_DS T_ID VS_T_ID HEADER_NO TB_SC   WHIP    LOB  \
0    20160401HHLG0  20160401   LG      HH         0     B  1.333  0.750
1    20160401HTNC0  20160401   HT      NC         0     T  1.750  0.804
2    20160401KTSK0  20160401   SK      KT         0     B  1.667  0.606
3    20160401LTWO0  20160401   WO      LT         0     B  1.444  0.846
4    20160401OBSS0  20160401   SS      OB         0     B  1.222  0.761
..             ...       ...  ...     ...       ...   ...    ...    ...
715  20161008HTHH0  20161008   HT      HH         0     T  1.759  0.723
716  20161008OBLG0  20161008   OB      LG         0     T  0.778  0.857
717  20161008SSSK0  20161008   SK      SS         0     B  1.444  0.686
718  20161009KTNC0  20161009   NC      KT         0     B  1.889  0.588
719  20161009WOLT0  20161009   LT      WO         0     B  1.444  0.615

       ERA     FIP  ...  vs_SECA  vs_TA  vs_XR  vs_ISO  vs_wOBA  vs_P_HRA_RT  \
0    3.000   7.333  ...    0.152  0.529  4.660   0.043    0.314        0.200
1    5.625  38.750  ...    0.567  1.000  6.228   0.267    0.488        0.143
2    8.000  39.444  ...    0.361  0.923  6.814   0.166    0.436        0.286
3    1.000   4.667  ...    0.189  0.571  3.672   0.054    0.330        0.071
4    4.000  37.333  ...    0.387  0.800  4.856   0.194    0.397        0.143
..     ...     ...  ...      ...    ...    ...     ...      ...          ...
715  4.655  35.345  ...    0.432  0.828  6.086   0.135    0.452        0.154
716  0.000  10.222  ...    0.207  0.296  0.306   0.035    0.202        0.250
717  6.000  34.111  ...    0.444  0.815  5.778   0.222    0.399        0.250
718  7.000   7.444  ...    0.263  0.875  6.684   0.079    0.420        0.100
719  5.000   7.667  ...    0.061  0.520  3.212   0.000    0.318        0.429

     vs_DER  vs_PF  vs_H_A  vs_WLS
0     0.742    939       0       0
1     0.696   1035       1       1
2     0.679    971       0       1
3     0.760    995       0       1
4     0.692   1062       0       1
..      ...    ...     ...     ...
715   0.710   1025       1       1
716   0.576    939       1       0
717   0.640    971       0       0
718   0.538   1035       0       1
719   0.700   1041       0       0

[720 rows x 68 columns]
               G_ID   GDAY_DS T_ID VS_T_ID HEADER_NO TB_SC   WHIP    LOB  \
0     20160401HHLG0  20160401   LG      HH         0     B  1.333  0.750
1     20160401HTNC0  20160401   HT      NC         0     T  1.750  0.804
2     20160401KTSK0  20160401   KT      SK         0     T  1.111  0.698
3     20160401LTWO0  20160401   LT      WO         0     T  1.222  0.909
4     20160401OBSS0  20160401   SS      OB         0     B  1.222  0.761
...             ...       ...  ...     ...       ...   ...    ...    ...
1435  20171003HTKT0  20171003   KT      HT         0     B  2.222  0.581
1436  20171003LGLT0  20171003   LT      LG         0     B  1.000  0.921
1437  20171003NCHH0  20171003   NC      HH         0     T  1.500  0.658
1438  20171003SKOB0  20171003   OB      SK         0     B  1.222  0.727
1439  20171003WOSS0  20171003   SS      WO         0     B  2.111  0.676

         ERA     FIP  ...  vs_SECA  vs_TA  vs_XR  vs_ISO  vs_wOBA  \
0      3.000   7.333  ...    0.152  0.529  4.660   0.043    0.314
1      5.625  38.750  ...    0.567  1.000  6.228   0.267    0.488
2      4.000  11.444  ...    0.389  0.667  4.274   0.222    0.333
3      0.000  13.667  ...    0.167  0.462  2.072   0.033    0.274
4      4.000  37.333  ...    0.387  0.800  4.856   0.194    0.397
...      ...     ...  ...      ...    ...    ...     ...      ...
1435  10.000  45.889  ...    0.622  1.292  9.620   0.244    0.553
1436   2.000  20.000  ...    0.485  0.630  3.658   0.242    0.318
1437   5.250  31.000  ...    0.288  0.703  7.372   0.154    0.350
1438   2.000   7.222  ...    0.171  0.481  2.926   0.028    0.281
1439   8.000  48.333  ...    0.537  1.148  9.534   0.293    0.508

      vs_P_HRA_RT  vs_DER  vs_PF  vs_H_A  vs_WLS
0           0.200   0.742    939       0       0
1           0.143   0.696   1035       1       1
2           0.375   0.679    971       1       0
3           0.000   0.645    995       1       0
4           0.143   0.692   1062       0       1
...           ...     ...    ...     ...     ...
1435        0.385   0.607   1020       0       1
1436        0.100   0.769   1041       0       0
1437        0.286   0.615   1025       1       0
1438        0.200   0.808    939       0       1
1439        0.308   0.667   1062       0       0

[1440 rows x 68 columns]
               G_ID   GDAY_DS T_ID VS_T_ID HEADER_NO TB_SC   WHIP    LOB  \
0     20160401HHLG0  20160401   HH      LG         0     T  1.147  0.690
1     20160401HTNC0  20160401   HT      NC         0     T  1.750  0.804
2     20160401KTSK0  20160401   KT      SK         0     T  1.111  0.698
3     20160401LTWO0  20160401   WO      LT         0     B  1.444  0.846
4     20160401OBSS0  20160401   OB      SS         0     T  1.111  0.909
...             ...       ...  ...     ...       ...   ...    ...    ...
2155  20181013LGSK0  20181013   LG      SK         0     T  1.333  0.952
2156  20181013LTHT0  20181013   LT      HT         0     T  0.778  0.875
2157  20181013NCHH0  20181013   HH      NC         0     B  1.556  0.612
2158  20181013WOSS0  20181013   SS      WO         0     B  1.333  0.761
2159  20181014OBLT0  20181014   LT      OB         0     B  1.111  0.625

        ERA     FIP  ...  vs_SECA  vs_TA  vs_XR  vs_ISO  vs_wOBA  vs_P_HRA_RT  \
0     3.176  23.059  ...    0.310  0.588  4.262   0.119    0.304        0.333
1     5.625  38.750  ...    0.567  1.000  6.228   0.267    0.488        0.143
2     4.000  11.444  ...    0.389  0.667  4.274   0.222    0.333        0.375
3     1.000   4.667  ...    0.189  0.571  3.672   0.054    0.330        0.071
4     1.000   7.667  ...    0.062  0.444  1.932   0.000    0.281        0.250
...     ...     ...  ...      ...    ...    ...     ...      ...          ...
2155  2.000  16.333  ...    0.105  0.667  5.044   0.079    0.344        0.250
2156  1.000   1.222  ...    0.031  0.321  0.686   0.031    0.214        0.143
2157  8.000  54.556  ...    0.571  0.889  6.562   0.285    0.435        0.286
2158  5.000  33.667  ...    0.429  0.778  5.362   0.229    0.384        0.400
2159  5.000  21.556  ...    0.206  0.556  3.414   0.089    0.314        0.333

      vs_DER  vs_PF  vs_H_A  vs_WLS
0      0.667    939       1       1
1      0.696   1035       1       1
2      0.679    971       1       0
3      0.760    995       0       1
4      0.786   1062       1       0
...      ...    ...     ...     ...
2155   0.704    971       1       0
2156   0.773   1004       1       0
2157   0.667   1025       0       0
2158   0.517   1062       0       0
2159   0.679   1041       0       1

[2160 rows x 68 columns]
               G_ID   GDAY_DS T_ID VS_T_ID HEADER_NO TB_SC   WHIP    LOB  \
0     20160401HHLG0  20160401   LG      HH         0     B  1.333  0.750
1     20160401HTNC0  20160401   HT      NC         0     T  1.750  0.804
2     20160401KTSK0  20160401   SK      KT         0     B  1.667  0.606
3     20160401LTWO0  20160401   WO      LT         0     B  1.444  0.846
4     20160401OBSS0  20160401   SS      OB         0     B  1.222  0.761
...             ...       ...  ...     ...       ...   ...    ...    ...
2875  20190929WOLT0  20190929   WO      LT         0     T  0.778  0.875
2876  20190930LTLG0  20190930   LG      LT         0     B  0.667  1.000
2877  20190930SKHH0  20190930   HH      SK         0     B  1.667  0.662
2878  20191001NCOB0  20191001   NC      OB         0     T  1.920  0.625
2879  20191001WOLT0  20191001   LT      WO         0     B  1.222  0.727

        ERA     FIP  ...  vs_SECA  vs_TA  vs_XR  vs_ISO  vs_wOBA  vs_P_HRA_RT  \
0     3.000   7.333  ...    0.152  0.529  4.660   0.043    0.314        0.200
1     5.625  38.750  ...    0.567  1.000  6.228   0.267    0.488        0.143
2     8.000  39.444  ...    0.361  0.923  6.814   0.166    0.436        0.286
3     1.000   4.667  ...    0.189  0.571  3.672   0.054    0.330        0.071
4     4.000  37.333  ...    0.387  0.800  4.856   0.194    0.397        0.143
...     ...     ...  ...      ...    ...    ...     ...      ...          ...
2875  1.000   1.000  ...    0.212  0.444  2.410   0.030    0.279        0.000
2876  0.000   8.111  ...    0.074  0.435  1.740   0.000    0.284        0.000
2877  6.000  26.000  ...    0.394  0.800  5.268   0.121    0.416        0.400
2878  5.400   1.560  ...    0.028  0.370  2.346   0.000    0.242        0.167
2879  1.000   7.000  ...    0.257  0.517  2.668   0.085    0.289        0.300

      vs_DER  vs_PF  vs_H_A  vs_WLS
0      0.742    939       0       0
1      0.696   1035       1       1
2      0.679    971       0       1
3      0.760    995       0       1
4      0.692   1062       0       1
...      ...    ...     ...     ...
2875   0.828   1041       1       0
2876   0.739    939       0       0
2877   0.724   1025       0       1
2878   0.528    939       1       1
2879   0.679   1041       0       1

[2880 rows x 68 columns]

               G_ID   GDAY_DS T_ID VS_T_ID HEADER_NO TB_SC   WHIP    LOB  ERA  \
0     20160401HHLG0  20160401   LG      HH         0     B  1.333  0.750  3.0
1     20160401HTNC0  20160401   NC      HT         0     B  1.222  0.755  4.0
2     20160401KTSK0  20160401   KT      SK         0     T  1.111  0.698  4.0
3     20160401LTWO0  20160401   WO      LT         0     B  1.444  0.846  1.0
4     20160401OBSS0  20160401   OB      SS         0     T  1.111  0.909  1.0
...             ...       ...  ...     ...       ...   ...    ...    ...  ...
3195  20200719HHLG0  20200719   LG      HH         0     B  1.000  0.800  2.0
3196  20200719KTNC0  20200719   NC      KT         0     B  0.667  0.870  2.0
3197  20200719LTSS0  20200719   LT      SS         0     T  1.111  1.047  1.0
3198  20200719OBHT0  20200719   HT      OB         0     B  1.444  0.515  8.0
3199  20200719WOSK0  20200719   SK      WO         0     B  1.111  0.833  3.0

         FIP  ...  vs_SECA  vs_TA  vs_XR  vs_ISO  vs_wOBA  vs_P_HRA_RT  \
0      7.333  ...    0.152  0.529  4.660   0.043    0.314        0.200
1     22.778  ...    0.382  0.667  4.170   0.177    0.361        0.100
2     11.444  ...    0.389  0.667  4.274   0.222    0.333        0.375
3      4.667  ...    0.189  0.571  3.672   0.054    0.330        0.071
4      7.667  ...    0.062  0.444  1.932   0.000    0.281        0.250
...      ...  ...      ...    ...    ...     ...      ...          ...
3195  -0.111  ...    0.118  0.444  2.258   0.059    0.246        0.125
3196  14.000  ...    0.156  0.333  1.278   0.094    0.198        0.000
3197  20.000  ...    0.258  0.577  2.898   0.097    0.307        0.000
3198  21.111  ...    0.351  0.852  6.038   0.162    0.396        0.364
3199  24.111  ...    0.242  0.556  3.238   0.091    0.318        0.333

      vs_DER  vs_PF  vs_H_A  vs_WLS
0      0.742    939       0       0
1      0.650   1035       0       0
2      0.679    971       1       0
3      0.760    995       0       1
4      0.786   1062       1       0
...      ...    ...     ...     ...
3195   0.778    939       0       0
3196   0.593   1035       0       0
3197   0.773   1062       1       0
3198   0.704   1004       0       1
3199   0.700    971       0       0

[3200 rows x 68 columns]